#### general settings
name: 'recommendation.cfg'

#### login OJ accounts
oj_username: 'your ytu OJ account'
oj_passwd : 'your password for ytu OJ account'

#### urls
oj_login_url: 'http://202.194.119.110/login.php'
oj_contest_down_url: 'http://202.194.119.110/contestrank.xls.php?cid='
oj_contest_down2_url: 'http://202.194.119.110/contestrank2.xls.php?cid='
oj_user_info_url: 'http://202.194.119.110/userinfo.php?user='
oj_user_latestAC_url: 'http://202.194.119.110/status.php?jresult=4&user_id='
oj_contest_url: 'http://202.194.119.110/contest.php'

#### datasets
datasets:
  root: 'data/'
  data_root: 'data/contest_csv/'
  generate_csv_root: 'data/generate_csv/'
  generate_file_name: 'generate.csv'
  recommendation_name: 'recommendation.csv'
  generate_tmp_file_name: 'generate_tmp.csv'
  generate_userinfo_name: 'user_info.csv'
  problemset_name: 'problem.csv'
  problemset_ratio_name: 'problem_r.csv'
  train:
    train_csv_root: 'data/'
    train_file_name: 'train.csv'
    train_f_file_name: 'train_factor.csv'
    train_p_file_name: 'train_prefer_class.csv'
  test:
    test_csv_root: 'data/'
    test_file_root: 'test.csv'

#### save plot image
plot_save: true
plot_save_path: 'data/plot_img/'

#### db cfg
db_host: 'localhost'
db_user: 'root'
db_pass: ''
db_name: 'test'

#### others cfg
recommend_num: 10
newbee_threshold: 30

log_path: 'log/'
log_name: 'run.log'

tmp_problem_path: 'data/_tmp/'



